#!/bin/sh
#
# Copyright (c) Josef "Jeff" Sipek, 2006-2011
#

USAGE=""
if [ -z "$GUILT_VERSION" ]; then
	echo "Invoking $GUILT directly is no longer supported." >&2
	exit 1
fi

_main() {

if  [ $# -gt 0 ]; then
	usage
fi

echo "$GIT_DIR/patches/$branch"
}
