#!/bin/sh
#
# Copyright (c) Josef "Jeff" Sipek, 2007-2011
#

USAGE="<new_name>"
if [ -z "$GUILT_VERSION" ]; then
	echo "Invoking $GUILT directly is no longer supported." >&2
	exit 1
fi

_main() {

if [ $# -ne 1 ]; then
	usage
fi

patch=`get_top`
if [ -z "$patch" ]; then
	die "No patches are applied."
fi

# make sure that there are no unapplied changes
if ! must_commit_first; then
	die "Uncommited changes detected. Refresh first."
fi

newpatch="$1"

if ! valid_patchname "$newpatch"; then
	die "The specified patch name contains invalid characters (:)."
fi

if [ -e "$GUILT_DIR/$branch/$newpatch" ]; then
	die "Patch \"$newpatch\" already exists. Choose another name."
fi

# copy the patch
mv "$GUILT_DIR/$branch/$patch" "$GUILT_DIR/$branch/$newpatch"

# replace the series & applied file references
series_rename_patch "$patch" "$newpatch"
applied_rename_patch "$patch" "$newpatch"
ref_rename_patch "$patch" "$newpatch"
rm -f $GUILT_DIR/$branch/$patch

}
